name: Execute E2E Tests

on:
  pull_request:
    paths:
      - 'ui/**'
      - 'server/**'
      - 'db/**'

defaults:
  run:
    working-directory: ./test/e2e

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm i
      - name: Test
        run: npm run test
      - name: Upload Test Output
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: TestContent
          path: |
            ./test/e2e/cypress/reports
            ./test/e2e/cypress/screenshots
            ./test/e2e/cypress/videos